server:
  port: 8088
spring:
  mail:
    default-encoding: utf-8
    host: mail.o-trial.com
    username: postmaster@o-trial.com
    password: Qr@77.88
    port: 587
    properties:
      mail:
        smtp:
          # 以下2行配置解决: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first
          starttls.enable: true
          ssl.trust: mail.o-trial.com
        debug: true